// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/hello/v1/hello.proto

package hellov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_DEGRADED    HealthCheckResponse_ServingStatus = 3 // 降级模式（部分中间件不可用）
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "DEGRADED",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
		"DEGRADED":    3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hello_v1_hello_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_proto_hello_v1_hello_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_hello_v1_hello_proto_rawDescGZIP(), []int{4, 0}
}

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_proto_hello_v1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_v1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_proto_hello_v1_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_v1_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_v1_hello_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_hello_v1_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_v1_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_hello_v1_hello_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HealthCheckRequest 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detailed      bool                   `protobuf:"varint,1,opt,name=detailed,proto3" json:"detailed,omitempty"` // 是否返回详细信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_hello_v1_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_v1_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_v1_hello_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckRequest) GetDetailed() bool {
	if x != nil {
		return x.Detailed
	}
	return false
}

// HealthCheckResponse 健康检查响应
type HealthCheckResponse struct {
	state   protoimpl.MessageState            `protogen:"open.v1"`
	Status  HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=hello.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"` // 服务状态
	Version string                            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                                // 服务版本
	Uptime  int64                             `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`                                                 // 运行时长(秒)
	// 各中间件状态
	Mongodb       *HealthCheckResponse_ComponentStatus `protobuf:"bytes,4,opt,name=mongodb,proto3" json:"mongodb,omitempty"` // MongoDB状态
	Redis         *HealthCheckResponse_ComponentStatus `protobuf:"bytes,5,opt,name=redis,proto3" json:"redis,omitempty"`     // Redis状态
	Kafka         *HealthCheckResponse_ComponentStatus `protobuf:"bytes,6,opt,name=kafka,proto3" json:"kafka,omitempty"`     // Kafka状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_hello_v1_hello_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_v1_hello_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_v1_hello_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *HealthCheckResponse) GetMongodb() *HealthCheckResponse_ComponentStatus {
	if x != nil {
		return x.Mongodb
	}
	return nil
}

func (x *HealthCheckResponse) GetRedis() *HealthCheckResponse_ComponentStatus {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *HealthCheckResponse) GetKafka() *HealthCheckResponse_ComponentStatus {
	if x != nil {
		return x.Kafka
	}
	return nil
}

type HealthCheckResponse_ComponentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`                  // 是否可用
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                       // 状态消息
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"` // 延迟(毫秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse_ComponentStatus) Reset() {
	*x = HealthCheckResponse_ComponentStatus{}
	mi := &file_proto_hello_v1_hello_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse_ComponentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse_ComponentStatus) ProtoMessage() {}

func (x *HealthCheckResponse_ComponentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_v1_hello_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse_ComponentStatus.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse_ComponentStatus) Descriptor() ([]byte, []int) {
	return file_proto_hello_v1_hello_proto_rawDescGZIP(), []int{4, 0}
}

func (x *HealthCheckResponse_ComponentStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *HealthCheckResponse_ComponentStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse_ComponentStatus) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_proto_hello_v1_hello_proto protoreflect.FileDescriptor

const file_proto_hello_v1_hello_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/hello/v1/hello.proto\x12\bhello.v1\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"S\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"0\n" +
	"\x12HealthCheckRequest\x12\x1a\n" +
	"\bdetailed\x18\x01 \x01(\bR\bdetailed\"\x93\x04\n" +
	"\x13HealthCheckResponse\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.hello.v1.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x03R\x06uptime\x12G\n" +
	"\amongodb\x18\x04 \x01(\v2-.hello.v1.HealthCheckResponse.ComponentStatusR\amongodb\x12C\n" +
	"\x05redis\x18\x05 \x01(\v2-.hello.v1.HealthCheckResponse.ComponentStatusR\x05redis\x12C\n" +
	"\x05kafka\x18\x06 \x01(\v2-.hello.v1.HealthCheckResponse.ComponentStatusR\x05kafka\x1ah\n" +
	"\x0fComponentStatus\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\"H\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\f\n" +
	"\bDEGRADED\x10\x032\xdd\x01\n" +
	"\fHelloService\x12A\n" +
	"\bSayHello\x12\x19.hello.v1.SayHelloRequest\x1a\x1a.hello.v1.SayHelloResponse\x12>\n" +
	"\n" +
	"ChatStream\x12\x15.hello.v1.ChatMessage\x1a\x15.hello.v1.ChatMessage(\x010\x01\x12J\n" +
	"\vHealthCheck\x12\x1c.hello.v1.HealthCheckRequest\x1a\x1d.hello.v1.HealthCheckResponseB!Z\x1fgo-gateway/api/hello/v1;hellov1b\x06proto3"

var (
	file_proto_hello_v1_hello_proto_rawDescOnce sync.Once
	file_proto_hello_v1_hello_proto_rawDescData []byte
)

func file_proto_hello_v1_hello_proto_rawDescGZIP() []byte {
	file_proto_hello_v1_hello_proto_rawDescOnce.Do(func() {
		file_proto_hello_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hello_v1_hello_proto_rawDesc), len(file_proto_hello_v1_hello_proto_rawDesc)))
	})
	return file_proto_hello_v1_hello_proto_rawDescData
}

var file_proto_hello_v1_hello_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_hello_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_hello_v1_hello_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0),      // 0: hello.v1.HealthCheckResponse.ServingStatus
	(*SayHelloRequest)(nil),                     // 1: hello.v1.SayHelloRequest
	(*SayHelloResponse)(nil),                    // 2: hello.v1.SayHelloResponse
	(*ChatMessage)(nil),                         // 3: hello.v1.ChatMessage
	(*HealthCheckRequest)(nil),                  // 4: hello.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),                 // 5: hello.v1.HealthCheckResponse
	(*HealthCheckResponse_ComponentStatus)(nil), // 6: hello.v1.HealthCheckResponse.ComponentStatus
}
var file_proto_hello_v1_hello_proto_depIdxs = []int32{
	0, // 0: hello.v1.HealthCheckResponse.status:type_name -> hello.v1.HealthCheckResponse.ServingStatus
	6, // 1: hello.v1.HealthCheckResponse.mongodb:type_name -> hello.v1.HealthCheckResponse.ComponentStatus
	6, // 2: hello.v1.HealthCheckResponse.redis:type_name -> hello.v1.HealthCheckResponse.ComponentStatus
	6, // 3: hello.v1.HealthCheckResponse.kafka:type_name -> hello.v1.HealthCheckResponse.ComponentStatus
	1, // 4: hello.v1.HelloService.SayHello:input_type -> hello.v1.SayHelloRequest
	3, // 5: hello.v1.HelloService.ChatStream:input_type -> hello.v1.ChatMessage
	4, // 6: hello.v1.HelloService.HealthCheck:input_type -> hello.v1.HealthCheckRequest
	2, // 7: hello.v1.HelloService.SayHello:output_type -> hello.v1.SayHelloResponse
	3, // 8: hello.v1.HelloService.ChatStream:output_type -> hello.v1.ChatMessage
	5, // 9: hello.v1.HelloService.HealthCheck:output_type -> hello.v1.HealthCheckResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_hello_v1_hello_proto_init() }
func file_proto_hello_v1_hello_proto_init() {
	if File_proto_hello_v1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hello_v1_hello_proto_rawDesc), len(file_proto_hello_v1_hello_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hello_v1_hello_proto_goTypes,
		DependencyIndexes: file_proto_hello_v1_hello_proto_depIdxs,
		EnumInfos:         file_proto_hello_v1_hello_proto_enumTypes,
		MessageInfos:      file_proto_hello_v1_hello_proto_msgTypes,
	}.Build()
	File_proto_hello_v1_hello_proto = out.File
	file_proto_hello_v1_hello_proto_goTypes = nil
	file_proto_hello_v1_hello_proto_depIdxs = nil
}
