// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/requirement/v1/requirement.proto

package requirementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequirementService_CreateRequirement_FullMethodName      = "/requirement.v1.RequirementService/CreateRequirement"
	RequirementService_GetRequirement_FullMethodName         = "/requirement.v1.RequirementService/GetRequirement"
	RequirementService_UpdateRequirement_FullMethodName      = "/requirement.v1.RequirementService/UpdateRequirement"
	RequirementService_DeleteRequirement_FullMethodName      = "/requirement.v1.RequirementService/DeleteRequirement"
	RequirementService_ListRequirements_FullMethodName       = "/requirement.v1.RequirementService/ListRequirements"
	RequirementService_LinkRequirements_FullMethodName       = "/requirement.v1.RequirementService/LinkRequirements"
	RequirementService_GetRelatedRequirements_FullMethodName = "/requirement.v1.RequirementService/GetRelatedRequirements"
	RequirementService_UploadDocument_FullMethodName         = "/requirement.v1.RequirementService/UploadDocument"
	RequirementService_GetDocument_FullMethodName            = "/requirement.v1.RequirementService/GetDocument"
)

// RequirementServiceClient is the client API for RequirementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ========== 需求服务 ==========
type RequirementServiceClient interface {
	// CRUD操作
	CreateRequirement(ctx context.Context, in *CreateRequirementRequest, opts ...grpc.CallOption) (*CreateRequirementResponse, error)
	GetRequirement(ctx context.Context, in *GetRequirementRequest, opts ...grpc.CallOption) (*GetRequirementResponse, error)
	UpdateRequirement(ctx context.Context, in *UpdateRequirementRequest, opts ...grpc.CallOption) (*UpdateRequirementResponse, error)
	DeleteRequirement(ctx context.Context, in *DeleteRequirementRequest, opts ...grpc.CallOption) (*DeleteRequirementResponse, error)
	ListRequirements(ctx context.Context, in *ListRequirementsRequest, opts ...grpc.CallOption) (*ListRequirementsResponse, error)
	// 关联关系
	LinkRequirements(ctx context.Context, in *LinkRequirementsRequest, opts ...grpc.CallOption) (*LinkRequirementsResponse, error)
	GetRelatedRequirements(ctx context.Context, in *GetRequirementRequest, opts ...grpc.CallOption) (*ListRequirementsResponse, error)
	// 文档管理
	UploadDocument(ctx context.Context, in *UploadDocumentRequest, opts ...grpc.CallOption) (*UploadDocumentResponse, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
}

type requirementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRequirementServiceClient(cc grpc.ClientConnInterface) RequirementServiceClient {
	return &requirementServiceClient{cc}
}

func (c *requirementServiceClient) CreateRequirement(ctx context.Context, in *CreateRequirementRequest, opts ...grpc.CallOption) (*CreateRequirementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRequirementResponse)
	err := c.cc.Invoke(ctx, RequirementService_CreateRequirement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) GetRequirement(ctx context.Context, in *GetRequirementRequest, opts ...grpc.CallOption) (*GetRequirementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRequirementResponse)
	err := c.cc.Invoke(ctx, RequirementService_GetRequirement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) UpdateRequirement(ctx context.Context, in *UpdateRequirementRequest, opts ...grpc.CallOption) (*UpdateRequirementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRequirementResponse)
	err := c.cc.Invoke(ctx, RequirementService_UpdateRequirement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) DeleteRequirement(ctx context.Context, in *DeleteRequirementRequest, opts ...grpc.CallOption) (*DeleteRequirementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRequirementResponse)
	err := c.cc.Invoke(ctx, RequirementService_DeleteRequirement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) ListRequirements(ctx context.Context, in *ListRequirementsRequest, opts ...grpc.CallOption) (*ListRequirementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRequirementsResponse)
	err := c.cc.Invoke(ctx, RequirementService_ListRequirements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) LinkRequirements(ctx context.Context, in *LinkRequirementsRequest, opts ...grpc.CallOption) (*LinkRequirementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkRequirementsResponse)
	err := c.cc.Invoke(ctx, RequirementService_LinkRequirements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) GetRelatedRequirements(ctx context.Context, in *GetRequirementRequest, opts ...grpc.CallOption) (*ListRequirementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRequirementsResponse)
	err := c.cc.Invoke(ctx, RequirementService_GetRelatedRequirements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) UploadDocument(ctx context.Context, in *UploadDocumentRequest, opts ...grpc.CallOption) (*UploadDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadDocumentResponse)
	err := c.cc.Invoke(ctx, RequirementService_UploadDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, RequirementService_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequirementServiceServer is the server API for RequirementService service.
// All implementations must embed UnimplementedRequirementServiceServer
// for forward compatibility.
//
// ========== 需求服务 ==========
type RequirementServiceServer interface {
	// CRUD操作
	CreateRequirement(context.Context, *CreateRequirementRequest) (*CreateRequirementResponse, error)
	GetRequirement(context.Context, *GetRequirementRequest) (*GetRequirementResponse, error)
	UpdateRequirement(context.Context, *UpdateRequirementRequest) (*UpdateRequirementResponse, error)
	DeleteRequirement(context.Context, *DeleteRequirementRequest) (*DeleteRequirementResponse, error)
	ListRequirements(context.Context, *ListRequirementsRequest) (*ListRequirementsResponse, error)
	// 关联关系
	LinkRequirements(context.Context, *LinkRequirementsRequest) (*LinkRequirementsResponse, error)
	GetRelatedRequirements(context.Context, *GetRequirementRequest) (*ListRequirementsResponse, error)
	// 文档管理
	UploadDocument(context.Context, *UploadDocumentRequest) (*UploadDocumentResponse, error)
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	mustEmbedUnimplementedRequirementServiceServer()
}

// UnimplementedRequirementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequirementServiceServer struct{}

func (UnimplementedRequirementServiceServer) CreateRequirement(context.Context, *CreateRequirementRequest) (*CreateRequirementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRequirement not implemented")
}
func (UnimplementedRequirementServiceServer) GetRequirement(context.Context, *GetRequirementRequest) (*GetRequirementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRequirement not implemented")
}
func (UnimplementedRequirementServiceServer) UpdateRequirement(context.Context, *UpdateRequirementRequest) (*UpdateRequirementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRequirement not implemented")
}
func (UnimplementedRequirementServiceServer) DeleteRequirement(context.Context, *DeleteRequirementRequest) (*DeleteRequirementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRequirement not implemented")
}
func (UnimplementedRequirementServiceServer) ListRequirements(context.Context, *ListRequirementsRequest) (*ListRequirementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRequirements not implemented")
}
func (UnimplementedRequirementServiceServer) LinkRequirements(context.Context, *LinkRequirementsRequest) (*LinkRequirementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkRequirements not implemented")
}
func (UnimplementedRequirementServiceServer) GetRelatedRequirements(context.Context, *GetRequirementRequest) (*ListRequirementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelatedRequirements not implemented")
}
func (UnimplementedRequirementServiceServer) UploadDocument(context.Context, *UploadDocumentRequest) (*UploadDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadDocument not implemented")
}
func (UnimplementedRequirementServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedRequirementServiceServer) mustEmbedUnimplementedRequirementServiceServer() {}
func (UnimplementedRequirementServiceServer) testEmbeddedByValue()                            {}

// UnsafeRequirementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequirementServiceServer will
// result in compilation errors.
type UnsafeRequirementServiceServer interface {
	mustEmbedUnimplementedRequirementServiceServer()
}

func RegisterRequirementServiceServer(s grpc.ServiceRegistrar, srv RequirementServiceServer) {
	// If the following call panics, it indicates UnimplementedRequirementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequirementService_ServiceDesc, srv)
}

func _RequirementService_CreateRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequirementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).CreateRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_CreateRequirement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).CreateRequirement(ctx, req.(*CreateRequirementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_GetRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequirementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).GetRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_GetRequirement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).GetRequirement(ctx, req.(*GetRequirementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_UpdateRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequirementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).UpdateRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_UpdateRequirement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).UpdateRequirement(ctx, req.(*UpdateRequirementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_DeleteRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequirementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).DeleteRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_DeleteRequirement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).DeleteRequirement(ctx, req.(*DeleteRequirementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_ListRequirements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequirementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).ListRequirements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_ListRequirements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).ListRequirements(ctx, req.(*ListRequirementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_LinkRequirements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequirementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).LinkRequirements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_LinkRequirements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).LinkRequirements(ctx, req.(*LinkRequirementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_GetRelatedRequirements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequirementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).GetRelatedRequirements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_GetRelatedRequirements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).GetRelatedRequirements(ctx, req.(*GetRequirementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_UploadDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).UploadDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_UploadDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).UploadDocument(ctx, req.(*UploadDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequirementService_ServiceDesc is the grpc.ServiceDesc for RequirementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequirementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "requirement.v1.RequirementService",
	HandlerType: (*RequirementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRequirement",
			Handler:    _RequirementService_CreateRequirement_Handler,
		},
		{
			MethodName: "GetRequirement",
			Handler:    _RequirementService_GetRequirement_Handler,
		},
		{
			MethodName: "UpdateRequirement",
			Handler:    _RequirementService_UpdateRequirement_Handler,
		},
		{
			MethodName: "DeleteRequirement",
			Handler:    _RequirementService_DeleteRequirement_Handler,
		},
		{
			MethodName: "ListRequirements",
			Handler:    _RequirementService_ListRequirements_Handler,
		},
		{
			MethodName: "LinkRequirements",
			Handler:    _RequirementService_LinkRequirements_Handler,
		},
		{
			MethodName: "GetRelatedRequirements",
			Handler:    _RequirementService_GetRelatedRequirements_Handler,
		},
		{
			MethodName: "UploadDocument",
			Handler:    _RequirementService_UploadDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _RequirementService_GetDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/requirement/v1/requirement.proto",
}

const (
	ExperienceService_CreateExperience_FullMethodName       = "/requirement.v1.ExperienceService/CreateExperience"
	ExperienceService_GetExperience_FullMethodName          = "/requirement.v1.ExperienceService/GetExperience"
	ExperienceService_ListExperiences_FullMethodName        = "/requirement.v1.ExperienceService/ListExperiences"
	ExperienceService_FindSimilarExperiences_FullMethodName = "/requirement.v1.ExperienceService/FindSimilarExperiences"
	ExperienceService_GetExperienceStats_FullMethodName     = "/requirement.v1.ExperienceService/GetExperienceStats"
)

// ExperienceServiceClient is the client API for ExperienceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ========== 经验服务 ==========
type ExperienceServiceClient interface {
	// 经验CRUD
	CreateExperience(ctx context.Context, in *CreateExperienceRequest, opts ...grpc.CallOption) (*CreateExperienceResponse, error)
	GetExperience(ctx context.Context, in *GetExperienceRequest, opts ...grpc.CallOption) (*GetExperienceResponse, error)
	ListExperiences(ctx context.Context, in *ListExperiencesRequest, opts ...grpc.CallOption) (*ListExperiencesResponse, error)
	// 经验检索（核心功能）
	FindSimilarExperiences(ctx context.Context, in *FindSimilarExperiencesRequest, opts ...grpc.CallOption) (*ListExperiencesResponse, error)
	// 经验统计
	GetExperienceStats(ctx context.Context, in *GetExperienceStatsRequest, opts ...grpc.CallOption) (*GetExperienceStatsResponse, error)
}

type experienceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExperienceServiceClient(cc grpc.ClientConnInterface) ExperienceServiceClient {
	return &experienceServiceClient{cc}
}

func (c *experienceServiceClient) CreateExperience(ctx context.Context, in *CreateExperienceRequest, opts ...grpc.CallOption) (*CreateExperienceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExperienceResponse)
	err := c.cc.Invoke(ctx, ExperienceService_CreateExperience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *experienceServiceClient) GetExperience(ctx context.Context, in *GetExperienceRequest, opts ...grpc.CallOption) (*GetExperienceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExperienceResponse)
	err := c.cc.Invoke(ctx, ExperienceService_GetExperience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *experienceServiceClient) ListExperiences(ctx context.Context, in *ListExperiencesRequest, opts ...grpc.CallOption) (*ListExperiencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExperiencesResponse)
	err := c.cc.Invoke(ctx, ExperienceService_ListExperiences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *experienceServiceClient) FindSimilarExperiences(ctx context.Context, in *FindSimilarExperiencesRequest, opts ...grpc.CallOption) (*ListExperiencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExperiencesResponse)
	err := c.cc.Invoke(ctx, ExperienceService_FindSimilarExperiences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *experienceServiceClient) GetExperienceStats(ctx context.Context, in *GetExperienceStatsRequest, opts ...grpc.CallOption) (*GetExperienceStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExperienceStatsResponse)
	err := c.cc.Invoke(ctx, ExperienceService_GetExperienceStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExperienceServiceServer is the server API for ExperienceService service.
// All implementations must embed UnimplementedExperienceServiceServer
// for forward compatibility.
//
// ========== 经验服务 ==========
type ExperienceServiceServer interface {
	// 经验CRUD
	CreateExperience(context.Context, *CreateExperienceRequest) (*CreateExperienceResponse, error)
	GetExperience(context.Context, *GetExperienceRequest) (*GetExperienceResponse, error)
	ListExperiences(context.Context, *ListExperiencesRequest) (*ListExperiencesResponse, error)
	// 经验检索（核心功能）
	FindSimilarExperiences(context.Context, *FindSimilarExperiencesRequest) (*ListExperiencesResponse, error)
	// 经验统计
	GetExperienceStats(context.Context, *GetExperienceStatsRequest) (*GetExperienceStatsResponse, error)
	mustEmbedUnimplementedExperienceServiceServer()
}

// UnimplementedExperienceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExperienceServiceServer struct{}

func (UnimplementedExperienceServiceServer) CreateExperience(context.Context, *CreateExperienceRequest) (*CreateExperienceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExperience not implemented")
}
func (UnimplementedExperienceServiceServer) GetExperience(context.Context, *GetExperienceRequest) (*GetExperienceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExperience not implemented")
}
func (UnimplementedExperienceServiceServer) ListExperiences(context.Context, *ListExperiencesRequest) (*ListExperiencesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExperiences not implemented")
}
func (UnimplementedExperienceServiceServer) FindSimilarExperiences(context.Context, *FindSimilarExperiencesRequest) (*ListExperiencesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindSimilarExperiences not implemented")
}
func (UnimplementedExperienceServiceServer) GetExperienceStats(context.Context, *GetExperienceStatsRequest) (*GetExperienceStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExperienceStats not implemented")
}
func (UnimplementedExperienceServiceServer) mustEmbedUnimplementedExperienceServiceServer() {}
func (UnimplementedExperienceServiceServer) testEmbeddedByValue()                           {}

// UnsafeExperienceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExperienceServiceServer will
// result in compilation errors.
type UnsafeExperienceServiceServer interface {
	mustEmbedUnimplementedExperienceServiceServer()
}

func RegisterExperienceServiceServer(s grpc.ServiceRegistrar, srv ExperienceServiceServer) {
	// If the following call panics, it indicates UnimplementedExperienceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExperienceService_ServiceDesc, srv)
}

func _ExperienceService_CreateExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExperienceServiceServer).CreateExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExperienceService_CreateExperience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExperienceServiceServer).CreateExperience(ctx, req.(*CreateExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExperienceService_GetExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExperienceServiceServer).GetExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExperienceService_GetExperience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExperienceServiceServer).GetExperience(ctx, req.(*GetExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExperienceService_ListExperiences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExperiencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExperienceServiceServer).ListExperiences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExperienceService_ListExperiences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExperienceServiceServer).ListExperiences(ctx, req.(*ListExperiencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExperienceService_FindSimilarExperiences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSimilarExperiencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExperienceServiceServer).FindSimilarExperiences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExperienceService_FindSimilarExperiences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExperienceServiceServer).FindSimilarExperiences(ctx, req.(*FindSimilarExperiencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExperienceService_GetExperienceStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExperienceStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExperienceServiceServer).GetExperienceStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExperienceService_GetExperienceStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExperienceServiceServer).GetExperienceStats(ctx, req.(*GetExperienceStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExperienceService_ServiceDesc is the grpc.ServiceDesc for ExperienceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExperienceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "requirement.v1.ExperienceService",
	HandlerType: (*ExperienceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExperience",
			Handler:    _ExperienceService_CreateExperience_Handler,
		},
		{
			MethodName: "GetExperience",
			Handler:    _ExperienceService_GetExperience_Handler,
		},
		{
			MethodName: "ListExperiences",
			Handler:    _ExperienceService_ListExperiences_Handler,
		},
		{
			MethodName: "FindSimilarExperiences",
			Handler:    _ExperienceService_FindSimilarExperiences_Handler,
		},
		{
			MethodName: "GetExperienceStats",
			Handler:    _ExperienceService_GetExperienceStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/requirement/v1/requirement.proto",
}
