// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/requirement/v1/requirement.proto

package requirementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 需求
type Requirement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority       string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"` // high/medium/low
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`     // backlog/in_progress/done/cancelled
	RelatedIds     []string               `protobuf:"bytes,6,rep,name=related_ids,json=relatedIds,proto3" json:"related_ids,omitempty"`
	Tags           []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	GeneratedFiles []string               `protobuf:"bytes,8,rep,name=generated_files,json=generatedFiles,proto3" json:"generated_files,omitempty"`
	Experiences    []*ExperienceRef       `protobuf:"bytes,9,rep,name=experiences,proto3" json:"experiences,omitempty"`
	CreatorId      string                 `protobuf:"bytes,10,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Requirement) Reset() {
	*x = Requirement{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirement) ProtoMessage() {}

func (x *Requirement) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirement.ProtoReflect.Descriptor instead.
func (*Requirement) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{0}
}

func (x *Requirement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Requirement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Requirement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Requirement) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Requirement) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Requirement) GetRelatedIds() []string {
	if x != nil {
		return x.RelatedIds
	}
	return nil
}

func (x *Requirement) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Requirement) GetGeneratedFiles() []string {
	if x != nil {
		return x.GeneratedFiles
	}
	return nil
}

func (x *Requirement) GetExperiences() []*ExperienceRef {
	if x != nil {
		return x.Experiences
	}
	return nil
}

func (x *Requirement) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Requirement) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Requirement) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Requirement) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// 经验引用
type ExperienceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExperienceId  string                 `protobuf:"bytes,1,opt,name=experience_id,json=experienceId,proto3" json:"experience_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // problem_solution / best_practice / pitfall
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperienceRef) Reset() {
	*x = ExperienceRef{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperienceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperienceRef) ProtoMessage() {}

func (x *ExperienceRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperienceRef.ProtoReflect.Descriptor instead.
func (*ExperienceRef) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{1}
}

func (x *ExperienceRef) GetExperienceId() string {
	if x != nil {
		return x.ExperienceId
	}
	return ""
}

func (x *ExperienceRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExperienceRef) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ExperienceRef) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// 经验
type Experience struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequirementId string                 `protobuf:"bytes,2,opt,name=requirement_id,json=requirementId,proto3" json:"requirement_id,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // problem_solution / best_practice / pitfall / pattern
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Solution      string                 `protobuf:"bytes,7,opt,name=solution,proto3" json:"solution,omitempty"`
	CodeExample   string                 `protobuf:"bytes,8,opt,name=code_example,json=codeExample,proto3" json:"code_example,omitempty"`
	FilePath      string                 `protobuf:"bytes,9,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	LineRange     []int32                `protobuf:"varint,10,rep,packed,name=line_range,json=lineRange,proto3" json:"line_range,omitempty"` // [start, end]
	Confidence    float64                `protobuf:"fixed64,11,opt,name=confidence,proto3" json:"confidence,omitempty"`
	TimesUsed     int32                  `protobuf:"varint,12,opt,name=times_used,json=timesUsed,proto3" json:"times_used,omitempty"`
	Technologies  []string               `protobuf:"bytes,13,rep,name=technologies,proto3" json:"technologies,omitempty"`
	Category      string                 `protobuf:"bytes,14,opt,name=category,proto3" json:"category,omitempty"` // database / api / security / performance
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Experience) Reset() {
	*x = Experience{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience) ProtoMessage() {}

func (x *Experience) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience.ProtoReflect.Descriptor instead.
func (*Experience) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{2}
}

func (x *Experience) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Experience) GetRequirementId() string {
	if x != nil {
		return x.RequirementId
	}
	return ""
}

func (x *Experience) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Experience) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Experience) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Experience) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Experience) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *Experience) GetCodeExample() string {
	if x != nil {
		return x.CodeExample
	}
	return ""
}

func (x *Experience) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Experience) GetLineRange() []int32 {
	if x != nil {
		return x.LineRange
	}
	return nil
}

func (x *Experience) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Experience) GetTimesUsed() int32 {
	if x != nil {
		return x.TimesUsed
	}
	return 0
}

func (x *Experience) GetTechnologies() []string {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *Experience) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Experience) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 文档
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequirementId string                 `protobuf:"bytes,2,opt,name=requirement_id,json=requirementId,proto3" json:"requirement_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"` // doc / md / pdf
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Summary       string                 `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	UploadedBy    string                 `protobuf:"bytes,8,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{3}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetRequirementId() string {
	if x != nil {
		return x.RequirementId
	}
	return ""
}

func (x *Document) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Document) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Document) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Document) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Document) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

func (x *Document) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

// 创建需求
type CreateRequirementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatorId     string                 `protobuf:"bytes,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequirementRequest) Reset() {
	*x = CreateRequirementRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequirementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequirementRequest) ProtoMessage() {}

func (x *CreateRequirementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequirementRequest.ProtoReflect.Descriptor instead.
func (*CreateRequirementRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRequirementRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRequirementRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRequirementRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateRequirementRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateRequirementRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type CreateRequirementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requirement   *Requirement           `protobuf:"bytes,1,opt,name=requirement,proto3" json:"requirement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequirementResponse) Reset() {
	*x = CreateRequirementResponse{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequirementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequirementResponse) ProtoMessage() {}

func (x *CreateRequirementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequirementResponse.ProtoReflect.Descriptor instead.
func (*CreateRequirementResponse) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRequirementResponse) GetRequirement() *Requirement {
	if x != nil {
		return x.Requirement
	}
	return nil
}

// 获取需求
type GetRequirementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequirementRequest) Reset() {
	*x = GetRequirementRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequirementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequirementRequest) ProtoMessage() {}

func (x *GetRequirementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequirementRequest.ProtoReflect.Descriptor instead.
func (*GetRequirementRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequirementRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRequirementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requirement   *Requirement           `protobuf:"bytes,1,opt,name=requirement,proto3" json:"requirement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequirementResponse) Reset() {
	*x = GetRequirementResponse{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequirementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequirementResponse) ProtoMessage() {}

func (x *GetRequirementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequirementResponse.ProtoReflect.Descriptor instead.
func (*GetRequirementResponse) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequirementResponse) GetRequirement() *Requirement {
	if x != nil {
		return x.Requirement
	}
	return nil
}

// 更新需求
type UpdateRequirementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Priority      *string                `protobuf:"bytes,4,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	Status        *string                `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequirementRequest) Reset() {
	*x = UpdateRequirementRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequirementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequirementRequest) ProtoMessage() {}

func (x *UpdateRequirementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequirementRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequirementRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRequirementRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequirementRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateRequirementRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRequirementRequest) GetPriority() string {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return ""
}

func (x *UpdateRequirementRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateRequirementRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateRequirementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requirement   *Requirement           `protobuf:"bytes,1,opt,name=requirement,proto3" json:"requirement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequirementResponse) Reset() {
	*x = UpdateRequirementResponse{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequirementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequirementResponse) ProtoMessage() {}

func (x *UpdateRequirementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequirementResponse.ProtoReflect.Descriptor instead.
func (*UpdateRequirementResponse) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRequirementResponse) GetRequirement() *Requirement {
	if x != nil {
		return x.Requirement
	}
	return nil
}

// 删除需求
type DeleteRequirementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequirementRequest) Reset() {
	*x = DeleteRequirementRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequirementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequirementRequest) ProtoMessage() {}

func (x *DeleteRequirementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequirementRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequirementRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequirementRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequirementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequirementResponse) Reset() {
	*x = DeleteRequirementResponse{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequirementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequirementResponse) ProtoMessage() {}

func (x *DeleteRequirementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequirementResponse.ProtoReflect.Descriptor instead.
func (*DeleteRequirementResponse) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRequirementResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 列出需求
type ListRequirementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Priority      *string                `protobuf:"bytes,4,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequirementsRequest) Reset() {
	*x = ListRequirementsRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequirementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequirementsRequest) ProtoMessage() {}

func (x *ListRequirementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequirementsRequest.ProtoReflect.Descriptor instead.
func (*ListRequirementsRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{12}
}

func (x *ListRequirementsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRequirementsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequirementsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListRequirementsRequest) GetPriority() string {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return ""
}

func (x *ListRequirementsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListRequirementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requirements  []*Requirement         `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequirementsResponse) Reset() {
	*x = ListRequirementsResponse{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequirementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequirementsResponse) ProtoMessage() {}

func (x *ListRequirementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequirementsResponse.ProtoReflect.Descriptor instead.
func (*ListRequirementsResponse) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{13}
}

func (x *ListRequirementsResponse) GetRequirements() []*Requirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *ListRequirementsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 关联需求
type LinkRequirementsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FromRequirementId string                 `protobuf:"bytes,1,opt,name=from_requirement_id,json=fromRequirementId,proto3" json:"from_requirement_id,omitempty"`
	ToRequirementId   string                 `protobuf:"bytes,2,opt,name=to_requirement_id,json=toRequirementId,proto3" json:"to_requirement_id,omitempty"`
	RelationType      string                 `protobuf:"bytes,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"` // blocks / blocked_by / relates_to / duplicates
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LinkRequirementsRequest) Reset() {
	*x = LinkRequirementsRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkRequirementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRequirementsRequest) ProtoMessage() {}

func (x *LinkRequirementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRequirementsRequest.ProtoReflect.Descriptor instead.
func (*LinkRequirementsRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{14}
}

func (x *LinkRequirementsRequest) GetFromRequirementId() string {
	if x != nil {
		return x.FromRequirementId
	}
	return ""
}

func (x *LinkRequirementsRequest) GetToRequirementId() string {
	if x != nil {
		return x.ToRequirementId
	}
	return ""
}

func (x *LinkRequirementsRequest) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

type LinkRequirementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkRequirementsResponse) Reset() {
	*x = LinkRequirementsResponse{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkRequirementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRequirementsResponse) ProtoMessage() {}

func (x *LinkRequirementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRequirementsResponse.ProtoReflect.Descriptor instead.
func (*LinkRequirementsResponse) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{15}
}

func (x *LinkRequirementsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 上传文档
type UploadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequirementId string                 `protobuf:"bytes,1,opt,name=requirement_id,json=requirementId,proto3" json:"requirement_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`          // doc / md / pdf
	FileContent   []byte                 `protobuf:"bytes,4,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"` // 文件二进制内容
	UploadedBy    string                 `protobuf:"bytes,5,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentRequest) Reset() {
	*x = UploadDocumentRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest) ProtoMessage() {}

func (x *UploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{16}
}

func (x *UploadDocumentRequest) GetRequirementId() string {
	if x != nil {
		return x.RequirementId
	}
	return ""
}

func (x *UploadDocumentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadDocumentRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *UploadDocumentRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *UploadDocumentRequest) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

type UploadDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentResponse) Reset() {
	*x = UploadDocumentResponse{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentResponse) ProtoMessage() {}

func (x *UploadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentResponse.ProtoReflect.Descriptor instead.
func (*UploadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{17}
}

func (x *UploadDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

// 获取文档
type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{18}
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{19}
}

func (x *GetDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

// 创建经验
type CreateExperienceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequirementId string                 `protobuf:"bytes,1,opt,name=requirement_id,json=requirementId,proto3" json:"requirement_id,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // problem_solution / best_practice / pitfall / pattern
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Solution      string                 `protobuf:"bytes,6,opt,name=solution,proto3" json:"solution,omitempty"`
	CodeExample   string                 `protobuf:"bytes,7,opt,name=code_example,json=codeExample,proto3" json:"code_example,omitempty"`
	FilePath      string                 `protobuf:"bytes,8,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	LineRange     []int32                `protobuf:"varint,9,rep,packed,name=line_range,json=lineRange,proto3" json:"line_range,omitempty"`
	Technologies  []string               `protobuf:"bytes,10,rep,name=technologies,proto3" json:"technologies,omitempty"`
	Category      string                 `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"` // database / api / security / performance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExperienceRequest) Reset() {
	*x = CreateExperienceRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExperienceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExperienceRequest) ProtoMessage() {}

func (x *CreateExperienceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExperienceRequest.ProtoReflect.Descriptor instead.
func (*CreateExperienceRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{20}
}

func (x *CreateExperienceRequest) GetRequirementId() string {
	if x != nil {
		return x.RequirementId
	}
	return ""
}

func (x *CreateExperienceRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateExperienceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateExperienceRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateExperienceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateExperienceRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *CreateExperienceRequest) GetCodeExample() string {
	if x != nil {
		return x.CodeExample
	}
	return ""
}

func (x *CreateExperienceRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CreateExperienceRequest) GetLineRange() []int32 {
	if x != nil {
		return x.LineRange
	}
	return nil
}

func (x *CreateExperienceRequest) GetTechnologies() []string {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *CreateExperienceRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CreateExperienceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Experience    *Experience            `protobuf:"bytes,1,opt,name=experience,proto3" json:"experience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExperienceResponse) Reset() {
	*x = CreateExperienceResponse{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExperienceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExperienceResponse) ProtoMessage() {}

func (x *CreateExperienceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExperienceResponse.ProtoReflect.Descriptor instead.
func (*CreateExperienceResponse) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{21}
}

func (x *CreateExperienceResponse) GetExperience() *Experience {
	if x != nil {
		return x.Experience
	}
	return nil
}

// 获取经验
type GetExperienceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExperienceRequest) Reset() {
	*x = GetExperienceRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExperienceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExperienceRequest) ProtoMessage() {}

func (x *GetExperienceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExperienceRequest.ProtoReflect.Descriptor instead.
func (*GetExperienceRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{22}
}

func (x *GetExperienceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetExperienceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Experience    *Experience            `protobuf:"bytes,1,opt,name=experience,proto3" json:"experience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExperienceResponse) Reset() {
	*x = GetExperienceResponse{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExperienceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExperienceResponse) ProtoMessage() {}

func (x *GetExperienceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExperienceResponse.ProtoReflect.Descriptor instead.
func (*GetExperienceResponse) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{23}
}

func (x *GetExperienceResponse) GetExperience() *Experience {
	if x != nil {
		return x.Experience
	}
	return nil
}

// 列出经验
type ListExperiencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Type          *string                `protobuf:"bytes,3,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Category      *string                `protobuf:"bytes,4,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Technologies  []string               `protobuf:"bytes,6,rep,name=technologies,proto3" json:"technologies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExperiencesRequest) Reset() {
	*x = ListExperiencesRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExperiencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExperiencesRequest) ProtoMessage() {}

func (x *ListExperiencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExperiencesRequest.ProtoReflect.Descriptor instead.
func (*ListExperiencesRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{24}
}

func (x *ListExperiencesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListExperiencesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListExperiencesRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ListExperiencesRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *ListExperiencesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListExperiencesRequest) GetTechnologies() []string {
	if x != nil {
		return x.Technologies
	}
	return nil
}

type ListExperiencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Experiences   []*Experience          `protobuf:"bytes,1,rep,name=experiences,proto3" json:"experiences,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExperiencesResponse) Reset() {
	*x = ListExperiencesResponse{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExperiencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExperiencesResponse) ProtoMessage() {}

func (x *ListExperiencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExperiencesResponse.ProtoReflect.Descriptor instead.
func (*ListExperiencesResponse) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{25}
}

func (x *ListExperiencesResponse) GetExperiences() []*Experience {
	if x != nil {
		return x.Experiences
	}
	return nil
}

func (x *ListExperiencesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 查找相似经验
type FindSimilarExperiencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Technologies  []string               `protobuf:"bytes,2,rep,name=technologies,proto3" json:"technologies,omitempty"`
	Category      *string                `protobuf:"bytes,3,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // 返回数量限制，默认10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSimilarExperiencesRequest) Reset() {
	*x = FindSimilarExperiencesRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSimilarExperiencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSimilarExperiencesRequest) ProtoMessage() {}

func (x *FindSimilarExperiencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSimilarExperiencesRequest.ProtoReflect.Descriptor instead.
func (*FindSimilarExperiencesRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{26}
}

func (x *FindSimilarExperiencesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FindSimilarExperiencesRequest) GetTechnologies() []string {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *FindSimilarExperiencesRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *FindSimilarExperiencesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 经验统计
type GetExperienceStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 可以添加过滤条件
	Category      *string  `protobuf:"bytes,1,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Technologies  []string `protobuf:"bytes,2,rep,name=technologies,proto3" json:"technologies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExperienceStatsRequest) Reset() {
	*x = GetExperienceStatsRequest{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExperienceStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExperienceStatsRequest) ProtoMessage() {}

func (x *GetExperienceStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExperienceStatsRequest.ProtoReflect.Descriptor instead.
func (*GetExperienceStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{27}
}

func (x *GetExperienceStatsRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *GetExperienceStatsRequest) GetTechnologies() []string {
	if x != nil {
		return x.Technologies
	}
	return nil
}

type GetExperienceStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalExperiences int64                  `protobuf:"varint,1,opt,name=total_experiences,json=totalExperiences,proto3" json:"total_experiences,omitempty"`
	ByType           map[string]int64       `protobuf:"bytes,2,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`                   // 按类型统计
	ByCategory       map[string]int64       `protobuf:"bytes,3,rep,name=by_category,json=byCategory,proto3" json:"by_category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`       // 按分类统计
	ByTechnology     map[string]int64       `protobuf:"bytes,4,rep,name=by_technology,json=byTechnology,proto3" json:"by_technology,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 按技术栈统计
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetExperienceStatsResponse) Reset() {
	*x = GetExperienceStatsResponse{}
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExperienceStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExperienceStatsResponse) ProtoMessage() {}

func (x *GetExperienceStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_requirement_v1_requirement_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExperienceStatsResponse.ProtoReflect.Descriptor instead.
func (*GetExperienceStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_requirement_v1_requirement_proto_rawDescGZIP(), []int{28}
}

func (x *GetExperienceStatsResponse) GetTotalExperiences() int64 {
	if x != nil {
		return x.TotalExperiences
	}
	return 0
}

func (x *GetExperienceStatsResponse) GetByType() map[string]int64 {
	if x != nil {
		return x.ByType
	}
	return nil
}

func (x *GetExperienceStatsResponse) GetByCategory() map[string]int64 {
	if x != nil {
		return x.ByCategory
	}
	return nil
}

func (x *GetExperienceStatsResponse) GetByTechnology() map[string]int64 {
	if x != nil {
		return x.ByTechnology
	}
	return nil
}

var File_api_requirement_v1_requirement_proto protoreflect.FileDescriptor

const file_api_requirement_v1_requirement_proto_rawDesc = "" +
	"\n" +
	"$api/requirement/v1/requirement.proto\x12\x0erequirement.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x04\n" +
	"\vRequirement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vrelated_ids\x18\x06 \x03(\tR\n" +
	"relatedIds\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12'\n" +
	"\x0fgenerated_files\x18\b \x03(\tR\x0egeneratedFiles\x12?\n" +
	"\vexperiences\x18\t \x03(\v2\x1d.requirement.v1.ExperienceRefR\vexperiences\x12\x1d\n" +
	"\n" +
	"creator_id\x18\n" +
	" \x01(\tR\tcreatorId\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12B\n" +
	"\fcompleted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vcompletedAt\x88\x01\x01B\x0f\n" +
	"\r_completed_at\"v\n" +
	"\rExperienceRef\x12#\n" +
	"\rexperience_id\x18\x01 \x01(\tR\fexperienceId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\"\xd8\x03\n" +
	"\n" +
	"Experience\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0erequirement_id\x18\x02 \x01(\tR\rrequirementId\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1a\n" +
	"\bsolution\x18\a \x01(\tR\bsolution\x12!\n" +
	"\fcode_example\x18\b \x01(\tR\vcodeExample\x12\x1b\n" +
	"\tfile_path\x18\t \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"line_range\x18\n" +
	" \x03(\x05R\tlineRange\x12\x1e\n" +
	"\n" +
	"confidence\x18\v \x01(\x01R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"times_used\x18\f \x01(\x05R\ttimesUsed\x12\"\n" +
	"\ftechnologies\x18\r \x03(\tR\ftechnologies\x12\x1a\n" +
	"\bcategory\x18\x0e \x01(\tR\bcategory\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xaa\x02\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0erequirement_id\x18\x02 \x01(\tR\rrequirementId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary\x12\x1f\n" +
	"\vuploaded_by\x18\b \x01(\tR\n" +
	"uploadedBy\x12;\n" +
	"\vuploaded_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\"\xa1\x01\n" +
	"\x18CreateRequirementRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x05 \x01(\tR\tcreatorId\"Z\n" +
	"\x19CreateRequirementResponse\x12=\n" +
	"\vrequirement\x18\x01 \x01(\v2\x1b.requirement.v1.RequirementR\vrequirement\"'\n" +
	"\x15GetRequirementRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x16GetRequirementResponse\x12=\n" +
	"\vrequirement\x18\x01 \x01(\v2\x1b.requirement.v1.RequirementR\vrequirement\"\xf0\x01\n" +
	"\x18UpdateRequirementRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x04 \x01(\tH\x02R\bpriority\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x03R\x06status\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tagsB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_priorityB\t\n" +
	"\a_status\"Z\n" +
	"\x19UpdateRequirementResponse\x12=\n" +
	"\vrequirement\x18\x01 \x01(\v2\x1b.requirement.v1.RequirementR\vrequirement\"*\n" +
	"\x18DeleteRequirementRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x19DeleteRequirementResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb4\x01\n" +
	"\x17ListRequirementsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x00R\x06status\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x04 \x01(\tH\x01R\bpriority\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tagsB\t\n" +
	"\a_statusB\v\n" +
	"\t_priority\"q\n" +
	"\x18ListRequirementsResponse\x12?\n" +
	"\frequirements\x18\x01 \x03(\v2\x1b.requirement.v1.RequirementR\frequirements\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x9a\x01\n" +
	"\x17LinkRequirementsRequest\x12.\n" +
	"\x13from_requirement_id\x18\x01 \x01(\tR\x11fromRequirementId\x12*\n" +
	"\x11to_requirement_id\x18\x02 \x01(\tR\x0ftoRequirementId\x12#\n" +
	"\rrelation_type\x18\x03 \x01(\tR\frelationType\"4\n" +
	"\x18LinkRequirementsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xbc\x01\n" +
	"\x15UploadDocumentRequest\x12%\n" +
	"\x0erequirement_id\x18\x01 \x01(\tR\rrequirementId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12!\n" +
	"\ffile_content\x18\x04 \x01(\fR\vfileContent\x12\x1f\n" +
	"\vuploaded_by\x18\x05 \x01(\tR\n" +
	"uploadedBy\"N\n" +
	"\x16UploadDocumentResponse\x124\n" +
	"\bdocument\x18\x01 \x01(\v2\x18.requirement.v1.DocumentR\bdocument\"$\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x13GetDocumentResponse\x124\n" +
	"\bdocument\x18\x01 \x01(\v2\x18.requirement.v1.DocumentR\bdocument\"\xdb\x02\n" +
	"\x17CreateExperienceRequest\x12%\n" +
	"\x0erequirement_id\x18\x01 \x01(\tR\rrequirementId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bsolution\x18\x06 \x01(\tR\bsolution\x12!\n" +
	"\fcode_example\x18\a \x01(\tR\vcodeExample\x12\x1b\n" +
	"\tfile_path\x18\b \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"line_range\x18\t \x03(\x05R\tlineRange\x12\"\n" +
	"\ftechnologies\x18\n" +
	" \x03(\tR\ftechnologies\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\"V\n" +
	"\x18CreateExperienceResponse\x12:\n" +
	"\n" +
	"experience\x18\x01 \x01(\v2\x1a.requirement.v1.ExperienceR\n" +
	"experience\"&\n" +
	"\x14GetExperienceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x15GetExperienceResponse\x12:\n" +
	"\n" +
	"experience\x18\x01 \x01(\v2\x1a.requirement.v1.ExperienceR\n" +
	"experience\"\xd1\x01\n" +
	"\x16ListExperiencesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\x04type\x18\x03 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x04 \x01(\tH\x01R\bcategory\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\"\n" +
	"\ftechnologies\x18\x06 \x03(\tR\ftechnologiesB\a\n" +
	"\x05_typeB\v\n" +
	"\t_category\"m\n" +
	"\x17ListExperiencesResponse\x12<\n" +
	"\vexperiences\x18\x01 \x03(\v2\x1a.requirement.v1.ExperienceR\vexperiences\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x9b\x01\n" +
	"\x1dFindSimilarExperiencesRequest\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\x12\"\n" +
	"\ftechnologies\x18\x02 \x03(\tR\ftechnologies\x12\x1f\n" +
	"\bcategory\x18\x03 \x01(\tH\x00R\bcategory\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limitB\v\n" +
	"\t_category\"m\n" +
	"\x19GetExperienceStatsRequest\x12\x1f\n" +
	"\bcategory\x18\x01 \x01(\tH\x00R\bcategory\x88\x01\x01\x12\"\n" +
	"\ftechnologies\x18\x02 \x03(\tR\ftechnologiesB\v\n" +
	"\t_category\"\x95\x04\n" +
	"\x1aGetExperienceStatsResponse\x12+\n" +
	"\x11total_experiences\x18\x01 \x01(\x03R\x10totalExperiences\x12O\n" +
	"\aby_type\x18\x02 \x03(\v26.requirement.v1.GetExperienceStatsResponse.ByTypeEntryR\x06byType\x12[\n" +
	"\vby_category\x18\x03 \x03(\v2:.requirement.v1.GetExperienceStatsResponse.ByCategoryEntryR\n" +
	"byCategory\x12a\n" +
	"\rby_technology\x18\x04 \x03(\v2<.requirement.v1.GetExperienceStatsResponse.ByTechnologyEntryR\fbyTechnology\x1a9\n" +
	"\vByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a=\n" +
	"\x0fByCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a?\n" +
	"\x11ByTechnologyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xa5\a\n" +
	"\x12RequirementService\x12h\n" +
	"\x11CreateRequirement\x12(.requirement.v1.CreateRequirementRequest\x1a).requirement.v1.CreateRequirementResponse\x12_\n" +
	"\x0eGetRequirement\x12%.requirement.v1.GetRequirementRequest\x1a&.requirement.v1.GetRequirementResponse\x12h\n" +
	"\x11UpdateRequirement\x12(.requirement.v1.UpdateRequirementRequest\x1a).requirement.v1.UpdateRequirementResponse\x12h\n" +
	"\x11DeleteRequirement\x12(.requirement.v1.DeleteRequirementRequest\x1a).requirement.v1.DeleteRequirementResponse\x12e\n" +
	"\x10ListRequirements\x12'.requirement.v1.ListRequirementsRequest\x1a(.requirement.v1.ListRequirementsResponse\x12e\n" +
	"\x10LinkRequirements\x12'.requirement.v1.LinkRequirementsRequest\x1a(.requirement.v1.LinkRequirementsResponse\x12i\n" +
	"\x16GetRelatedRequirements\x12%.requirement.v1.GetRequirementRequest\x1a(.requirement.v1.ListRequirementsResponse\x12_\n" +
	"\x0eUploadDocument\x12%.requirement.v1.UploadDocumentRequest\x1a&.requirement.v1.UploadDocumentResponse\x12V\n" +
	"\vGetDocument\x12\".requirement.v1.GetDocumentRequest\x1a#.requirement.v1.GetDocumentResponse2\x9b\x04\n" +
	"\x11ExperienceService\x12e\n" +
	"\x10CreateExperience\x12'.requirement.v1.CreateExperienceRequest\x1a(.requirement.v1.CreateExperienceResponse\x12\\\n" +
	"\rGetExperience\x12$.requirement.v1.GetExperienceRequest\x1a%.requirement.v1.GetExperienceResponse\x12b\n" +
	"\x0fListExperiences\x12&.requirement.v1.ListExperiencesRequest\x1a'.requirement.v1.ListExperiencesResponse\x12p\n" +
	"\x16FindSimilarExperiences\x12-.requirement.v1.FindSimilarExperiencesRequest\x1a'.requirement.v1.ListExperiencesResponse\x12k\n" +
	"\x12GetExperienceStats\x12).requirement.v1.GetExperienceStatsRequest\x1a*.requirement.v1.GetExperienceStatsResponseB-Z+go-gateway/api/requirement/v1;requirementv1b\x06proto3"

var (
	file_api_requirement_v1_requirement_proto_rawDescOnce sync.Once
	file_api_requirement_v1_requirement_proto_rawDescData []byte
)

func file_api_requirement_v1_requirement_proto_rawDescGZIP() []byte {
	file_api_requirement_v1_requirement_proto_rawDescOnce.Do(func() {
		file_api_requirement_v1_requirement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_requirement_v1_requirement_proto_rawDesc), len(file_api_requirement_v1_requirement_proto_rawDesc)))
	})
	return file_api_requirement_v1_requirement_proto_rawDescData
}

var file_api_requirement_v1_requirement_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_requirement_v1_requirement_proto_goTypes = []any{
	(*Requirement)(nil),                   // 0: requirement.v1.Requirement
	(*ExperienceRef)(nil),                 // 1: requirement.v1.ExperienceRef
	(*Experience)(nil),                    // 2: requirement.v1.Experience
	(*Document)(nil),                      // 3: requirement.v1.Document
	(*CreateRequirementRequest)(nil),      // 4: requirement.v1.CreateRequirementRequest
	(*CreateRequirementResponse)(nil),     // 5: requirement.v1.CreateRequirementResponse
	(*GetRequirementRequest)(nil),         // 6: requirement.v1.GetRequirementRequest
	(*GetRequirementResponse)(nil),        // 7: requirement.v1.GetRequirementResponse
	(*UpdateRequirementRequest)(nil),      // 8: requirement.v1.UpdateRequirementRequest
	(*UpdateRequirementResponse)(nil),     // 9: requirement.v1.UpdateRequirementResponse
	(*DeleteRequirementRequest)(nil),      // 10: requirement.v1.DeleteRequirementRequest
	(*DeleteRequirementResponse)(nil),     // 11: requirement.v1.DeleteRequirementResponse
	(*ListRequirementsRequest)(nil),       // 12: requirement.v1.ListRequirementsRequest
	(*ListRequirementsResponse)(nil),      // 13: requirement.v1.ListRequirementsResponse
	(*LinkRequirementsRequest)(nil),       // 14: requirement.v1.LinkRequirementsRequest
	(*LinkRequirementsResponse)(nil),      // 15: requirement.v1.LinkRequirementsResponse
	(*UploadDocumentRequest)(nil),         // 16: requirement.v1.UploadDocumentRequest
	(*UploadDocumentResponse)(nil),        // 17: requirement.v1.UploadDocumentResponse
	(*GetDocumentRequest)(nil),            // 18: requirement.v1.GetDocumentRequest
	(*GetDocumentResponse)(nil),           // 19: requirement.v1.GetDocumentResponse
	(*CreateExperienceRequest)(nil),       // 20: requirement.v1.CreateExperienceRequest
	(*CreateExperienceResponse)(nil),      // 21: requirement.v1.CreateExperienceResponse
	(*GetExperienceRequest)(nil),          // 22: requirement.v1.GetExperienceRequest
	(*GetExperienceResponse)(nil),         // 23: requirement.v1.GetExperienceResponse
	(*ListExperiencesRequest)(nil),        // 24: requirement.v1.ListExperiencesRequest
	(*ListExperiencesResponse)(nil),       // 25: requirement.v1.ListExperiencesResponse
	(*FindSimilarExperiencesRequest)(nil), // 26: requirement.v1.FindSimilarExperiencesRequest
	(*GetExperienceStatsRequest)(nil),     // 27: requirement.v1.GetExperienceStatsRequest
	(*GetExperienceStatsResponse)(nil),    // 28: requirement.v1.GetExperienceStatsResponse
	nil,                                   // 29: requirement.v1.GetExperienceStatsResponse.ByTypeEntry
	nil,                                   // 30: requirement.v1.GetExperienceStatsResponse.ByCategoryEntry
	nil,                                   // 31: requirement.v1.GetExperienceStatsResponse.ByTechnologyEntry
	(*timestamppb.Timestamp)(nil),         // 32: google.protobuf.Timestamp
}
var file_api_requirement_v1_requirement_proto_depIdxs = []int32{
	1,  // 0: requirement.v1.Requirement.experiences:type_name -> requirement.v1.ExperienceRef
	32, // 1: requirement.v1.Requirement.created_at:type_name -> google.protobuf.Timestamp
	32, // 2: requirement.v1.Requirement.updated_at:type_name -> google.protobuf.Timestamp
	32, // 3: requirement.v1.Requirement.completed_at:type_name -> google.protobuf.Timestamp
	32, // 4: requirement.v1.Experience.created_at:type_name -> google.protobuf.Timestamp
	32, // 5: requirement.v1.Document.uploaded_at:type_name -> google.protobuf.Timestamp
	0,  // 6: requirement.v1.CreateRequirementResponse.requirement:type_name -> requirement.v1.Requirement
	0,  // 7: requirement.v1.GetRequirementResponse.requirement:type_name -> requirement.v1.Requirement
	0,  // 8: requirement.v1.UpdateRequirementResponse.requirement:type_name -> requirement.v1.Requirement
	0,  // 9: requirement.v1.ListRequirementsResponse.requirements:type_name -> requirement.v1.Requirement
	3,  // 10: requirement.v1.UploadDocumentResponse.document:type_name -> requirement.v1.Document
	3,  // 11: requirement.v1.GetDocumentResponse.document:type_name -> requirement.v1.Document
	2,  // 12: requirement.v1.CreateExperienceResponse.experience:type_name -> requirement.v1.Experience
	2,  // 13: requirement.v1.GetExperienceResponse.experience:type_name -> requirement.v1.Experience
	2,  // 14: requirement.v1.ListExperiencesResponse.experiences:type_name -> requirement.v1.Experience
	29, // 15: requirement.v1.GetExperienceStatsResponse.by_type:type_name -> requirement.v1.GetExperienceStatsResponse.ByTypeEntry
	30, // 16: requirement.v1.GetExperienceStatsResponse.by_category:type_name -> requirement.v1.GetExperienceStatsResponse.ByCategoryEntry
	31, // 17: requirement.v1.GetExperienceStatsResponse.by_technology:type_name -> requirement.v1.GetExperienceStatsResponse.ByTechnologyEntry
	4,  // 18: requirement.v1.RequirementService.CreateRequirement:input_type -> requirement.v1.CreateRequirementRequest
	6,  // 19: requirement.v1.RequirementService.GetRequirement:input_type -> requirement.v1.GetRequirementRequest
	8,  // 20: requirement.v1.RequirementService.UpdateRequirement:input_type -> requirement.v1.UpdateRequirementRequest
	10, // 21: requirement.v1.RequirementService.DeleteRequirement:input_type -> requirement.v1.DeleteRequirementRequest
	12, // 22: requirement.v1.RequirementService.ListRequirements:input_type -> requirement.v1.ListRequirementsRequest
	14, // 23: requirement.v1.RequirementService.LinkRequirements:input_type -> requirement.v1.LinkRequirementsRequest
	6,  // 24: requirement.v1.RequirementService.GetRelatedRequirements:input_type -> requirement.v1.GetRequirementRequest
	16, // 25: requirement.v1.RequirementService.UploadDocument:input_type -> requirement.v1.UploadDocumentRequest
	18, // 26: requirement.v1.RequirementService.GetDocument:input_type -> requirement.v1.GetDocumentRequest
	20, // 27: requirement.v1.ExperienceService.CreateExperience:input_type -> requirement.v1.CreateExperienceRequest
	22, // 28: requirement.v1.ExperienceService.GetExperience:input_type -> requirement.v1.GetExperienceRequest
	24, // 29: requirement.v1.ExperienceService.ListExperiences:input_type -> requirement.v1.ListExperiencesRequest
	26, // 30: requirement.v1.ExperienceService.FindSimilarExperiences:input_type -> requirement.v1.FindSimilarExperiencesRequest
	27, // 31: requirement.v1.ExperienceService.GetExperienceStats:input_type -> requirement.v1.GetExperienceStatsRequest
	5,  // 32: requirement.v1.RequirementService.CreateRequirement:output_type -> requirement.v1.CreateRequirementResponse
	7,  // 33: requirement.v1.RequirementService.GetRequirement:output_type -> requirement.v1.GetRequirementResponse
	9,  // 34: requirement.v1.RequirementService.UpdateRequirement:output_type -> requirement.v1.UpdateRequirementResponse
	11, // 35: requirement.v1.RequirementService.DeleteRequirement:output_type -> requirement.v1.DeleteRequirementResponse
	13, // 36: requirement.v1.RequirementService.ListRequirements:output_type -> requirement.v1.ListRequirementsResponse
	15, // 37: requirement.v1.RequirementService.LinkRequirements:output_type -> requirement.v1.LinkRequirementsResponse
	13, // 38: requirement.v1.RequirementService.GetRelatedRequirements:output_type -> requirement.v1.ListRequirementsResponse
	17, // 39: requirement.v1.RequirementService.UploadDocument:output_type -> requirement.v1.UploadDocumentResponse
	19, // 40: requirement.v1.RequirementService.GetDocument:output_type -> requirement.v1.GetDocumentResponse
	21, // 41: requirement.v1.ExperienceService.CreateExperience:output_type -> requirement.v1.CreateExperienceResponse
	23, // 42: requirement.v1.ExperienceService.GetExperience:output_type -> requirement.v1.GetExperienceResponse
	25, // 43: requirement.v1.ExperienceService.ListExperiences:output_type -> requirement.v1.ListExperiencesResponse
	25, // 44: requirement.v1.ExperienceService.FindSimilarExperiences:output_type -> requirement.v1.ListExperiencesResponse
	28, // 45: requirement.v1.ExperienceService.GetExperienceStats:output_type -> requirement.v1.GetExperienceStatsResponse
	32, // [32:46] is the sub-list for method output_type
	18, // [18:32] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_requirement_v1_requirement_proto_init() }
func file_api_requirement_v1_requirement_proto_init() {
	if File_api_requirement_v1_requirement_proto != nil {
		return
	}
	file_api_requirement_v1_requirement_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_requirement_v1_requirement_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_requirement_v1_requirement_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_requirement_v1_requirement_proto_msgTypes[24].OneofWrappers = []any{}
	file_api_requirement_v1_requirement_proto_msgTypes[26].OneofWrappers = []any{}
	file_api_requirement_v1_requirement_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_requirement_v1_requirement_proto_rawDesc), len(file_api_requirement_v1_requirement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_requirement_v1_requirement_proto_goTypes,
		DependencyIndexes: file_api_requirement_v1_requirement_proto_depIdxs,
		MessageInfos:      file_api_requirement_v1_requirement_proto_msgTypes,
	}.Build()
	File_api_requirement_v1_requirement_proto = out.File
	file_api_requirement_v1_requirement_proto_goTypes = nil
	file_api_requirement_v1_requirement_proto_depIdxs = nil
}
